QT += core gui widgets

CONFIG += c++17

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    main.cpp \
    src/combat/attackbox.cpp \
    src/combat/collision.cpp \
    src/combat/skill.cpp \
    src/core/gamewidget.cpp \
    src/core/mainwindow.cpp \
    src/entity/character.cpp \
    src/entity/enemy.cpp \
    src/entity/entity.cpp \
    src/entity/player.cpp \
    src/ui/hud.cpp \
    src/ui/resultwidget.cpp \
    src/ui/startmenu.cpp

HEADERS += \
    src/combat/attackbox.h \
    src/combat/collision.h \
    src/combat/skill.h \
    src/core/gameconfig.h \
    src/core/gametypes.h \
    src/core/gamewidget.h \
    src/core/mainwindow.h \
    src/entity/character.h \
    src/entity/enemy.h \
    src/entity/entity.h \
    src/entity/player.h \
    src/ui/hud.h \
    src/ui/resultwidget.h \
    src/ui/startmenu.h

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

RESOURCES += \
    rescource.qrc

DISTFILES += \
    assets/background/end.png \
    assets/background/lose.png \
    assets/background/win.png \
    assets/enemy/box_down_attack_1.png \
    assets/enemy/box_down_attack_2.png \
    assets/enemy/box_down_attack_3.png \
    assets/enemy/box_down_attack_4.png \
    assets/enemy/box_down_attack_5.png \
    assets/enemy/box_down_attack_6.png \
    assets/enemy/box_down_run_1.png \
    assets/enemy/box_down_run_2.png \
    assets/enemy/box_down_run_3.png \
    assets/enemy/box_down_run_4.png \
    assets/enemy/box_down_run_5.png \
    assets/enemy/box_down_run_6.png \
    assets/enemy/box_down_still.png \
    assets/enemy/box_left_attack_1.png \
    assets/enemy/box_left_attack_2.png \
    assets/enemy/box_left_attack_3.png \
    assets/enemy/box_left_attack_4.png \
    assets/enemy/box_left_attack_5.png \
    assets/enemy/box_left_attack_6.png \
    assets/enemy/box_left_run_1.png \
    assets/enemy/box_left_run_2.png \
    assets/enemy/box_left_run_3.png \
    assets/enemy/box_left_run_4.png \
    assets/enemy/box_left_run_5.png \
    assets/enemy/box_left_run_6.png \
    assets/enemy/box_left_still.png \
    assets/enemy/box_right_attack_1.png \
    assets/enemy/box_right_attack_2.png \
    assets/enemy/box_right_attack_3.png \
    assets/enemy/box_right_attack_4.png \
    assets/enemy/box_right_attack_5.png \
    assets/enemy/box_right_attack_6.png \
    assets/enemy/box_right_run_0.png \
    assets/enemy/box_right_run_1.png \
    assets/enemy/box_right_run_2.png \
    assets/enemy/box_right_run_3.png \
    assets/enemy/box_right_run_4.png \
    assets/enemy/box_right_run_5.png \
    assets/enemy/box_right_run_6.png \
    assets/enemy/box_right_still.png \
    assets/enemy/box_up_attack_1.png \
    assets/enemy/box_up_attack_2.png \
    assets/enemy/box_up_attack_3.png \
    assets/enemy/box_up_attack_4.png \
    assets/enemy/box_up_attack_5.png \
    assets/enemy/box_up_attack_6.png \
    assets/enemy/box_up_run_1.png \
    assets/enemy/box_up_run_2.png \
    assets/enemy/box_up_run_3.png \
    assets/enemy/box_up_run_4.png \
    assets/enemy/box_up_run_5.png \
    assets/enemy/box_up_run_6.png \
    assets/enemy/box_up_still.png \
    assets/enemy/ocat_down_attack_0.png \
    assets/enemy/ocat_down_attack_1.png \
    assets/enemy/ocat_down_attack_2.png \
    assets/enemy/ocat_down_attack_3.png \
    assets/enemy/ocat_down_attack_4.png \
    assets/enemy/ocat_down_attack_5.png \
    assets/enemy/ocat_down_attack_6.png \
    assets/enemy/ocat_down_ha_0.png \
    assets/enemy/ocat_down_ha_1.png \
    assets/enemy/ocat_down_ha_2.png \
    assets/enemy/ocat_down_ha_3.png \
    assets/enemy/ocat_down_ha_4.png \
    assets/enemy/ocat_down_ha_5.png \
    assets/enemy/ocat_down_ha_6.png \
    assets/enemy/ocat_down_plusattack_0.png \
    assets/enemy/ocat_down_plusattack_1.png \
    assets/enemy/ocat_down_plusattack_2.png \
    assets/enemy/ocat_down_plusattack_3.png \
    assets/enemy/ocat_down_plusattack_4.png \
    assets/enemy/ocat_down_plusattack_5.png \
    assets/enemy/ocat_down_plusattack_6.png \
    assets/enemy/ocat_down_run_1.png \
    assets/enemy/ocat_down_run_2.png \
    assets/enemy/ocat_down_run_3.png \
    assets/enemy/ocat_down_run_4.png \
    assets/enemy/ocat_down_run_5.png \
    assets/enemy/ocat_down_run_6.png \
    assets/enemy/ocat_down_still.png \
    assets/enemy/ocat_left_ha_1.png \
    assets/enemy/ocat_left_ha_2.png \
    assets/enemy/ocat_left_ha_3.png \
    assets/enemy/ocat_left_ha_4.png \
    assets/enemy/ocat_left_ha_5.png \
    assets/enemy/ocat_left_ha_6.png \
    assets/enemy/ocat_left_run_1.png \
    assets/enemy/ocat_left_run_2.png \
    assets/enemy/ocat_left_run_3.png \
    assets/enemy/ocat_left_run_4.png \
    assets/enemy/ocat_left_still.png \
    assets/enemy/ocat_right_attack_0.png \
    assets/enemy/ocat_right_attack_1.png \
    assets/enemy/ocat_right_attack_2.png \
    assets/enemy/ocat_right_attack_3.png \
    assets/enemy/ocat_right_attack_4.png \
    assets/enemy/ocat_right_attack_5.png \
    assets/enemy/ocat_right_attack_6.png \
    assets/enemy/ocat_right_ha_0.png \
    assets/enemy/ocat_right_ha_1.png \
    assets/enemy/ocat_right_ha_2.png \
    assets/enemy/ocat_right_ha_3.png \
    assets/enemy/ocat_right_ha_4.png \
    assets/enemy/ocat_right_ha_5.png \
    assets/enemy/ocat_right_ha_6.png \
    assets/enemy/ocat_right_run_1.png \
    assets/enemy/ocat_right_run_2.png \
    assets/enemy/ocat_right_run_3.png \
    assets/enemy/ocat_right_run_4.png \
    assets/enemy/ocat_right_still.png \
    assets/enemy/ocat_up_attack_1.png \
    assets/enemy/ocat_up_attack_2.png \
    assets/enemy/ocat_up_attack_3.png \
    assets/enemy/ocat_up_attack_4.png \
    assets/enemy/ocat_up_attack_5.png \
    assets/enemy/ocat_up_attack_6.png \
    assets/enemy/ocat_up_ha_0.png \
    assets/enemy/ocat_up_ha_1.png \
    assets/enemy/ocat_up_ha_2.png \
    assets/enemy/ocat_up_ha_3.png \
    assets/enemy/ocat_up_ha_4.png \
    assets/enemy/ocat_up_ha_5.png \
    assets/enemy/ocat_up_ha_6.png \
    assets/enemy/ocat_up_plusattack_1.png \
    assets/enemy/ocat_up_plusattack_2.png \
    assets/enemy/ocat_up_plusattack_3.png \
    assets/enemy/ocat_up_plusattack_4.png \
    assets/enemy/ocat_up_plusattack_5.png \
    assets/enemy/ocat_up_plusattack_6.png \
    assets/enemy/ocat_up_run_1.png \
    assets/enemy/ocat_up_run_2.png \
    assets/enemy/ocat_up_run_3.png \
    assets/enemy/ocat_up_run_4.png \
    assets/enemy/ocat_up_run_5.png \
    assets/enemy/ocat_up_run_6.png \
    assets/enemy/ocat_up_still.png \
    assets/player/player_down_attack_0.png \
    assets/player/player_down_attack_1.png \
    assets/player/player_down_attack_2.png \
    assets/player/player_down_attack_3.png \
    assets/player/player_down_attack_4.png \
    assets/player/player_down_attack_5.png \
    assets/player/player_down_attack_6.png \
    assets/player/player_down_ha_0.png \
    assets/player/player_down_ha_1.png \
    assets/player/player_down_ha_2.png \
    assets/player/player_down_ha_3.png \
    assets/player/player_down_ha_4.png \
    assets/player/player_down_ha_5.png \
    assets/player/player_down_ha_6.png \
    assets/player/player_down_plusattack_0.png \
    assets/player/player_down_plusattack_1.png \
    assets/player/player_down_plusattack_2.png \
    assets/player/player_down_plusattack_3.png \
    assets/player/player_down_plusattack_4.png \
    assets/player/player_down_plusattack_5.png \
    assets/player/player_down_plusattack_6 .png \
    assets/player/player_down_run_1.png \
    assets/player/player_down_run_2.png \
    assets/player/player_down_run_3.png \
    assets/player/player_down_still.png \
    assets/player/player_left_attack_0.png \
    assets/player/player_left_attack_1.png \
    assets/player/player_left_attack_2.png \
    assets/player/player_left_attack_3.png \
    assets/player/player_left_attack_4.png \
    assets/player/player_left_attack_5.png \
    assets/player/player_left_attack_6.png \
    assets/player/player_left_ha_0.png \
    assets/player/player_left_ha_1.png \
    assets/player/player_left_ha_2.png \
    assets/player/player_left_ha_3.png \
    assets/player/player_left_ha_4.png \
    assets/player/player_left_ha_5.png \
    assets/player/player_left_ha_6.png \
    assets/player/player_left_plusattack_0.png \
    assets/player/player_left_plusattack_1.png \
    assets/player/player_left_plusattack_2.png \
    assets/player/player_left_plusattack_3.png \
    assets/player/player_left_plusattack_4.png \
    assets/player/player_left_plusattack_5.png \
    assets/player/player_left_plusattack_6.png \
    assets/player/player_left_run_1.png \
    assets/player/player_left_run_2.png \
    assets/player/player_left_run_3.png \
    assets/player/player_left_run_4.png \
    assets/player/player_left_still.png \
    assets/player/player_right_attack_0.png \
    assets/player/player_right_attack_1.png \
    assets/player/player_right_attack_2.png \
    assets/player/player_right_attack_3.png \
    assets/player/player_right_attack_4.png \
    assets/player/player_right_attack_5.png \
    assets/player/player_right_attack_6.png \
    assets/player/player_right_ha_0.png \
    assets/player/player_right_ha_1.png \
    assets/player/player_right_ha_2.png \
    assets/player/player_right_ha_3.png \
    assets/player/player_right_ha_4.png \
    assets/player/player_right_ha_5.png \
    assets/player/player_right_ha_6.png \
    assets/player/player_right_plusattack_0.png \
    assets/player/player_right_plusattack_1.png \
    assets/player/player_right_plusattack_2.png \
    assets/player/player_right_plusattack_3.png \
    assets/player/player_right_plusattack_4.png \
    assets/player/player_right_plusattack_5.png \
    assets/player/player_right_plusattack_6.png \
    assets/player/player_right_run_1.png \
    assets/player/player_right_run_2.png \
    assets/player/player_right_run_3.png \
    assets/player/player_right_run_4.png \
    assets/player/player_right_still.png \
    assets/player/player_up_attack_0.png \
    assets/player/player_up_attack_1.png \
    assets/player/player_up_attack_2.png \
    assets/player/player_up_attack_3.png \
    assets/player/player_up_attack_4.png \
    assets/player/player_up_attack_5.png \
    assets/player/player_up_attack_6.png \
    assets/player/player_up_ha_0.png \
    assets/player/player_up_ha_1.png \
    assets/player/player_up_ha_2.png \
    assets/player/player_up_ha_3.png \
    assets/player/player_up_ha_4.png \
    assets/player/player_up_ha_5.png \
    assets/player/player_up_ha_6.png \
    assets/player/player_up_plusattack_0 .png \
    assets/player/player_up_plusattack_1.png \
    assets/player/player_up_plusattack_2.png \
    assets/player/player_up_plusattack_3.png \
    assets/player/player_up_plusattack_4.png \
    assets/player/player_up_plusattack_5.png \
    assets/player/player_up_plusattack_6 .png \
    assets/player/player_up_run_1.png \
    assets/player/player_up_run_2.png \
    assets/player/player_up_run_3.png \
    assets/player/player_up_run_4.png \
    assets/player/player_up_run_5.png \
    assets/player/player_up_run_6.png \
    assets/player/player_up_still_0.png \
    assets/sound/box_attack.mp3 \
    assets/sound/end.mp3 \
    assets/sound/lose.mp3 \
    assets/sound/ocat_attack.mp3 \
    assets/sound/ocat_plusattack.mp3 \
    assets/sound/player_attack.mp3 \
    assets/sound/player_plusattack.mp3 \
    assets/sound/win.mp3
